version: '2'

services:
  # ============================= Rocketchat ==================================
  rocketchat:
    image: rocket.chat:0.69.2
    restart: unless-stopped
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - ADMIN_USERNAME=admin
      - ADMIN_PASS=admin
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128
  # =============================== Coach =================================  
  coach:
    container_name: coach
    build:
      context: .
      dockerfile: ./docker/coach.Dockerfile
    ports:
      - 80:80
    environment:
      - AUGMENTATION_FACTOR=50
      - VALIDATION_SPLIT=0.2
  # ================================= Bot =====================================
  bot:
    image: lappis/bottis_bot:latest
    restart: unless-stopped
    command: make run-rocketchat 
    env_file:
      - docker/bot.env
    ports:
      - 5005:5005
      - 5002:5002
    depends_on:
      - actions
      - coach

  actions:
    build:
      context: .
      dockerfile: ./docker/actions.Dockerfile
    ports:
      - 5055:5055
    volumes:
      - ./actions:/bot/actions
      - ./actions/Makefile:/bot/Makefile
    command: "make run-actions"

  # ============================ Telegram Bot =================================
  telegram_bot:
      build:
        context: .
        dockerfile: ./docker/bot.Dockerfile
      environment:
        - TELEGRAM_BOT_USERNAME=lappisbot
        - TELEGRAM_TOKEN=token
        - TELEGRAM_WEBHOOK=your_webhook_server/webhooks/telegram/webhook
      ports:
        - 5001:5001
      depends_on:
        - actions
      volumes:
        - ./bot:/bot
        - ./scripts:/scripts
      command: sh -c "make run-telegram"


